### ISSUE TITLE
Issues with Ivy

### ISSUE THREAD

**Issue by AnimaLupi** [ndr/ngx-route-params-input#5]
Hello,

I've tried importing your module in a project using Angular 9.1.3 (latest at the time I'm writing) and I'm getting this error:

```
ERROR in node_modules/ngx-route-params-input/lib/ngx-route-params-input.module.d.ts:1:22 - 
error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an 
NgModule class.
    
    This likely means that the library (ngx-route-params-input) which declares 
NgxRouteParamsInputModule has not been processed correctly by ngcc, or is not compatible with 
Angular Ivy. Check if a newer version of the library is available, and update if soi. Also consider 
checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    1 export declare class NgxRouteParamsInputModule {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~
```

Did you experience any issue with Ivy?

In any case, thank for your work. The Angular router limitation about the way data is passed to component inputs is a big problem for component reuse and I'm really surprised the core team hasn't addressed it.

**Comment by ndr** [comment]
@AnimaLupi  Can you please provide your package.json and basic code?

**Comment by AnimaLupi** [comment]
@ndr No idea what happened but it's not giving me that error anymore.
I only de-installed and re-installed your package and it was ok.
Guess the issue was more Ivy compiler or angular-cli related. My apologies!

**Comment by ndr** [comment]
@AnimaLupi anyway thank you for your activity. Seems like it is a common problem:
https://github.com/angular/angular/issues/35399#issuecomment-586734020
